name: trigger-pipeline-with-post-request
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Request To PipeLine Server
      id: request
      uses: fjogeleit/http-request-action@v1.12.0
      with:
        preventFailureOnNoResponse: true
        url: 'http://43.138.213.187:4400/start'
        method: POST
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"host":"43.138.213.187","account":"root","ssh_file_path":"/root/.ssh","key_type":"ed25519","path":"/root/javaProject/rasberry-Home-Backend/rashome","image_name":"iot/backend","container_name":"rasHome","port":"12580"}'
    - name: Show Response
      run: |
        echo ${{ steps.request.outputs.response }}
        echo ${{ steps.request.outputs.headers }}
