name: trigger-pipeline-with-post-request
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1.12.0
      with:
        url: http://43.138.213.187:4400/start
        method: POST
        contentType: application/json
        data: '{"host":"43.138.213.187","account":"root","ssh_file_path":"/root/.ssh","key_type":"ed25519","path":"/root/javaProject/rasberry-Home-Backend/rashome","image_name":"iot/backend","container_name":"rasHome","port":"12580"}'
        timeout: 20
